/*
 * Journey-map sheet generator
 * --------------------------------------------------------------------------
 * Turns the extracted geodata in ./data into the layered SVG map sheet
 * consumed by Scripts/journey-map.js:
 *
 *   node _src/tools/journey/build-map.mjs
 *
 * Layers: Vietnam (Natural Earth 10m), neighbouring countries clipped to the
 * region (NE 50m), Mekong + Red River centerlines (NE 50m), country name
 * positions, and the itinerary legs routed along the NE 10m road network
 * (see data/route-legs.json — generated by a Dijkstra pass over the roads).
 *
 * `proj` are the plate-carrée parameters used for everything, so the runtime
 * can project stop lat/lng with the same formula:
 *   x = (lng - proj.lng0) * proj.kx
 *   y = (proj.lat1 - lat) * proj.ky
 * `focusH` is Vietnam's height in sheet units — the runtime scales the map
 * so the country (not the whole sheet) is MAP_VH × viewport height.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '../../..');
const DATA = (f) => JSON.parse(fs.readFileSync(path.join(HERE, 'data', f), 'utf8'));

const BBOX = { lng0: 95, lat0: 3, lng1: 117, lat1: 27 };
const VN_LAT = { min: 8.58, max: 23.34 }; // Vietnam extent, defines focusH
const PAD = 8;

const midLat = (BBOX.lat0 + BBOX.lat1) / 2;
const ky = 600 / (VN_LAT.max - VN_LAT.min); // Vietnam ≈ 600 units tall
const kx = ky * Math.cos((midLat * Math.PI) / 180);
const lng0 = BBOX.lng0 - PAD / kx;
const lat1 = BBOX.lat1 + PAD / ky;
const width = Math.round((BBOX.lng1 - lng0) * kx + PAD);
const height = Math.round((lat1 - BBOX.lat0) * ky + PAD);
const focusH = (VN_LAT.max - VN_LAT.min) * ky;

const project = ([lng, lat]) => [(lng - lng0) * kx, (lat1 - lat) * ky];

function simplify(points, tol) {
  if (points.length <= 4) return points;
  const sq = tol * tol;
  const keep = new Uint8Array(points.length);
  keep[0] = keep[points.length - 1] = 1;
  const stack = [[0, points.length - 1]];
  while (stack.length) {
    const [a, b] = stack.pop();
    const [ax, ay] = points[a];
    const [bx, by] = points[b];
    const dx = bx - ax;
    const dy = by - ay;
    const len2 = dx * dx + dy * dy || 1;
    let worst = -1;
    let worstD = sq;
    for (let i = a + 1; i < b; i++) {
      const [px, py] = points[i];
      const t = Math.max(0, Math.min(1, ((px - ax) * dx + (py - ay) * dy) / len2));
      const ex = px - (ax + t * dx);
      const ey = py - (ay + t * dy);
      const d = ex * ex + ey * ey;
      if (d > worstD) {
        worstD = d;
        worst = i;
      }
    }
    if (worst > 0) {
      keep[worst] = 1;
      stack.push([a, worst], [worst, b]);
    }
  }
  return points.filter((_, i) => keep[i]);
}

function toPath(points, close) {
  let d = '';
  let px = null;
  let py = null;
  points.forEach(([x, y], i) => {
    const rx = +x.toFixed(1);
    const ry = +y.toFixed(1);
    if (rx === px && ry === py) return;
    d += i === 0 ? `M${rx} ${ry}` : `L${rx} ${ry}`;
    px = rx;
    py = ry;
  });
  return close ? d + 'Z' : d;
}

const ring = (r, tol, close = true) => toPath(simplify(r.map(project), tol), close);

// Vietnam — 10m detail, light simplification
const focus = DATA('vnm10.json').map((r) => ring(r, 0.55));

// Neighbours — flatten all clipped rings, slightly stronger simplification
const neighbors = [];
DATA('neighbors.json').forEach((c) => c.rings.forEach((r) => neighbors.push(ring(r, 0.8))));

// Rivers — open polylines
const rivers = DATA('rivers.json').map((l) => ring(l, 0.6, false));

// Itinerary legs along roads — ordered: stop i → i+1 (extras = upcoming)
const route = DATA('route-legs.json').map((leg) =>
  simplify(leg.pts.map(project), 0.4).map(([x, y]) => [+x.toFixed(1), +y.toFixed(1)])
);

// Country name anchors (lat/lng chosen to sit inside each country)
const labels = [
  { name: 'CHINA', lat: 23.4, lng: 106.5 },
  { name: 'LAOS', lat: 17.9, lng: 104.9 },
  { name: 'CAMBODIA', lat: 12.4, lng: 104.9 },
  { name: 'THAILAND', lat: 15.6, lng: 101.2 }
].map((l) => {
  const [x, y] = project([l.lng, l.lat]);
  return { name: l.name, x: +x.toFixed(1), y: +y.toFixed(1) };
});

const out = `/* Generated by _src/tools/journey/build-map.mjs — do not edit by hand.
 * Geometry: Natural Earth (10m Vietnam/roads, 50m neighbours/rivers)
 * via world-atlas@2.0.2 and nvkelso/natural-earth-vector. */
window.__JOURNEY_OUTLINES__ = window.__JOURNEY_OUTLINES__ || {};
window.__JOURNEY_OUTLINES__.vietnam = {
  width: ${width},
  height: ${height},
  focusH: ${+focusH.toFixed(1)},
  proj: { lng0: ${+lng0.toFixed(5)}, lat1: ${+lat1.toFixed(5)}, kx: ${+kx.toFixed(5)}, ky: ${+ky.toFixed(5)} },
  focus: ${JSON.stringify(focus)},
  neighbors: ${JSON.stringify(neighbors)},
  rivers: ${JSON.stringify(rivers)},
  labels: ${JSON.stringify(labels)},
  route: ${JSON.stringify(route)}
};
`;
const dest = path.join(ROOT, 'Scripts', 'journey-outlines', 'vietnam.js');
fs.writeFileSync(dest, out);
console.log(`vietnam sheet ${width}x${height} (focusH ${focusH.toFixed(0)}) → ${path.relative(ROOT, dest)} (${(out.length / 1024).toFixed(1)} KB)`);
console.log(`legs: ${route.map((l) => l.length).join(', ')} pts`);
