/*
 * Journey-map outline generator
 * --------------------------------------------------------------------------
 * Turns a country GeoJSON (Natural Earth, via world-atlas 50m) into the
 * compact SVG outline consumed by Scripts/journey-map.js.
 *
 *   node _src/tools/journey/build-outline.mjs
 *
 * Output: Scripts/journey-outlines/<id>.js exposing
 *   window.__JOURNEY_OUTLINES__[<id>] = { width, height, proj, paths }
 *
 * `proj` are the plate-carrée parameters used to project the outline, so the
 * runtime can place stop markers from plain lat/lng with the same formula:
 *   x = (lng - proj.lng0) * proj.kx
 *   y = (proj.lat1 - lat) * proj.ky
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '../../..');

const COUNTRIES = [
  {
    id: 'vietnam',
    geojson: path.join(HERE, 'vnm.geo.json'),
    height: 600, // px height of the projected map
    pad: 8, // viewBox padding around the geometry
    tolerance: 0.7 // Douglas–Peucker tolerance, in output px
  }
];

/* Recursive Douglas–Peucker on a [[x,y],...] open/closed ring */
function simplify(points, tol) {
  if (points.length <= 4) return points;
  const sq = tol * tol;
  const keep = new Uint8Array(points.length);
  keep[0] = keep[points.length - 1] = 1;
  const stack = [[0, points.length - 1]];
  while (stack.length) {
    const [a, b] = stack.pop();
    const [ax, ay] = points[a];
    const [bx, by] = points[b];
    const dx = bx - ax;
    const dy = by - ay;
    const len2 = dx * dx + dy * dy || 1;
    let worst = -1;
    let worstD = sq;
    for (let i = a + 1; i < b; i++) {
      const [px, py] = points[i];
      const t = Math.max(0, Math.min(1, ((px - ax) * dx + (py - ay) * dy) / len2));
      const ex = px - (ax + t * dx);
      const ey = py - (ay + t * dy);
      const d = ex * ex + ey * ey;
      if (d > worstD) {
        worstD = d;
        worst = i;
      }
    }
    if (worst > 0) {
      keep[worst] = 1;
      stack.push([a, worst], [worst, b]);
    }
  }
  return points.filter((_, i) => keep[i]);
}

function ringToPath(points) {
  let d = '';
  let px = null;
  let py = null;
  points.forEach(([x, y], i) => {
    const rx = +x.toFixed(1);
    const ry = +y.toFixed(1);
    if (rx === px && ry === py) return;
    d += i === 0 ? `M${rx} ${ry}` : `L${rx} ${ry}`;
    px = rx;
    py = ry;
  });
  return d + 'Z';
}

for (const c of COUNTRIES) {
  const gj = JSON.parse(fs.readFileSync(c.geojson, 'utf8'));
  const rings = gj.geometry.coordinates.map((poly) => poly[0]);

  let minLng = Infinity;
  let maxLng = -Infinity;
  let minLat = Infinity;
  let maxLat = -Infinity;
  rings.flat().forEach(([lng, lat]) => {
    minLng = Math.min(minLng, lng);
    maxLng = Math.max(maxLng, lng);
    minLat = Math.min(minLat, lat);
    maxLat = Math.max(maxLat, lat);
  });

  const midLat = (minLat + maxLat) / 2;
  const ky = c.height / (maxLat - minLat);
  const kx = ky * Math.cos((midLat * Math.PI) / 180);
  // fold the padding into the projection origin so runtime stays one formula
  const lng0 = minLng - c.pad / kx;
  const lat1 = maxLat + c.pad / ky;
  const width = Math.round((maxLng - lng0) * kx + c.pad);
  const height = Math.round((lat1 - minLat) * ky + c.pad);

  const project = ([lng, lat]) => [(lng - lng0) * kx, (lat1 - lat) * ky];

  let kept = 0;
  const paths = rings.map((ring) => {
    const projected = ring.map(project);
    const slim = projected.length > 50 ? simplify(projected, c.tolerance) : projected;
    kept += slim.length;
    return ringToPath(slim);
  });

  const out = `/* Generated by _src/tools/journey/build-outline.mjs — do not edit by hand.
 * Geometry: Natural Earth 1:50m via world-atlas@2.0.2. */
window.__JOURNEY_OUTLINES__ = window.__JOURNEY_OUTLINES__ || {};
window.__JOURNEY_OUTLINES__[${JSON.stringify(c.id)}] = {
  width: ${width},
  height: ${height},
  proj: { lng0: ${+lng0.toFixed(5)}, lat1: ${+lat1.toFixed(5)}, kx: ${+kx.toFixed(5)}, ky: ${+ky.toFixed(5)} },
  paths: ${JSON.stringify(paths)}
};
`;
  const dest = path.join(ROOT, 'Scripts', 'journey-outlines', `${c.id}.js`);
  fs.writeFileSync(dest, out);
  console.log(`${c.id}: ${rings.length} rings, ${kept} pts → ${path.relative(ROOT, dest)} (${out.length} bytes), viewBox 0 0 ${width} ${height}`);
}
