/*
 * Journey map — giant scroll-following background (travel posts)
 * --------------------------------------------------------------------------
 * Draws the whole country as a huge, faint black-and-white background behind
 * the diary. The reader's position is pinned to the diary timeline-dot
 * column on the left of the days: the marker stays anchored there while the
 * country itself glides around behind the text. While a city's section is on
 * screen the map rests; crossing into the next city, the map slides so the
 * next stop arrives under the marker, revealing more of the country and the
 * itinerary. The drawn route ends at the last published stop; upcoming stops
 * are sketched in dotted grey.
 *
 * Inputs (set by the page before this script runs):
 *   window.__JOURNEY__          { outline, stops[], upcoming[] }
 *   window.__JOURNEY_OUTLINES__ projected country paths + projection params
 *                               (generated by _src/tools/journey/build-outline.mjs)
 *
 * Stops carry plain lat/lng; they are projected here with the same
 * plate-carrée parameters used for the outline. Each stop's `anchor` is the
 * id of its section heading in the article — scroll progress is measured
 * against those headings, so the map needs no per-post pixel tuning.
 * Purely decorative: aria-hidden, pointer-events none, desktop only.
 */
(function () {
  'use strict';

  var cfg = window.__JOURNEY__;
  var outlines = window.__JOURNEY_OUTLINES__;
  if (!cfg || !outlines || !outlines[cfg.outline]) return;
  var map = outlines[cfg.outline];

  var article = document.querySelector('.post-content');
  if (!article) return;

  var SVG_NS = 'http://www.w3.org/2000/svg';
  var DWELL = 0.6; // fraction of each section spent resting on its stop
  var REF = 0.42; // reading line, as a fraction of viewport height
  var MAP_VH = 1.6; // country height relative to the viewport — "giant"
  var DOT_X = -16; // anchor just left of the diary day-dot column, clear of headings

  function project(s) {
    return {
      x: (s.lng - map.proj.lng0) * map.proj.kx,
      y: (map.proj.lat1 - s.lat) * map.proj.ky
    };
  }

  var stops = cfg.stops
    .map(function (s) {
      var el = document.getElementById(s.anchor);
      if (!el) return null;
      var p = project(s);
      return { label: s.label, side: s.labelSide || 'left', ux: p.x, uy: p.y, el: el };
    })
    .filter(Boolean);
  if (stops.length < 2) return;

  var upcoming = (cfg.upcoming || []).map(function (s) {
    var p = project(s);
    return { label: s.label, side: s.labelSide || 'right', ux: p.x, uy: p.y };
  });

  /* ---- Leg geometry (screen px, rebuilt on resize): gentle quadratic bow
     toward the seaward (east) side. Arc lengths are sampled so marker
     position and stroke reveal agree. ---- */
  function quadAt(leg, t) {
    var u = 1 - t;
    return {
      x: u * u * leg.a.x + 2 * u * t * leg.c.x + t * t * leg.b.x,
      y: u * u * leg.a.y + 2 * u * t * leg.c.y + t * t * leg.b.y
    };
  }

  function buildLeg(a, b) {
    var dx = b.x - a.x;
    var dy = b.y - a.y;
    var span = Math.sqrt(dx * dx + dy * dy) || 1;
    var nx = dy / span;
    var ny = -dx / span;
    if (nx < 0) { nx = -nx; ny = -ny; } // bow east
    if (Math.abs(nx) < 0.25 && ny > 0) { nx = -nx; ny = -ny; } // near-horizontal: bow north
    var bow = Math.min(30, span * 0.16);
    var leg = {
      a: a,
      b: b,
      c: { x: (a.x + b.x) / 2 + nx * bow, y: (a.y + b.y) / 2 + ny * bow }
    };
    var N = 48;
    var cum = [0];
    var prev = a;
    for (var i = 1; i <= N; i++) {
      var p = quadAt(leg, i / N);
      cum.push(cum[i - 1] + Math.hypot(p.x - prev.x, p.y - prev.y));
      prev = p;
    }
    leg.samples = cum;
    leg.len = cum[N];
    return leg;
  }

  /* Point at a given arc-length fraction (lookup + lerp) */
  function pointAtFraction(leg, f) {
    var target = f * leg.len;
    var cum = leg.samples;
    var lo = 0;
    var hi = cum.length - 1;
    while (lo < hi - 1) {
      var mid = (lo + hi) >> 1;
      if (cum[mid] < target) lo = mid; else hi = mid;
    }
    var seg = cum[hi] - cum[lo] || 1;
    var t = (lo + (target - cum[lo]) / seg) / (cum.length - 1);
    return quadAt(leg, t);
  }

  function legD(leg) {
    return 'M' + leg.a.x.toFixed(1) + ' ' + leg.a.y.toFixed(1) +
      'Q' + leg.c.x.toFixed(1) + ' ' + leg.c.y.toFixed(1) +
      ' ' + leg.b.x.toFixed(1) + ' ' + leg.b.y.toFixed(1);
  }

  /* ---- Build the SVG ---- */
  function svgEl(tag, attrs, parent) {
    var el = document.createElementNS(SVG_NS, tag);
    for (var k in attrs) el.setAttribute(k, attrs[k]);
    if (parent) parent.appendChild(el);
    return el;
  }

  var container = document.createElement('div');
  container.className = 'journey-map';
  container.setAttribute('aria-hidden', 'true');

  var svg = svgEl('svg', {}, container);

  /* The country outline keeps its generated unit coordinates and is scaled
     by transform (crisp 1px coastline via non-scaling strokes). The route
     layer is rebuilt in screen px on resize, so dashes, dots and labels
     stay at their natural size. Both layers share the same pan. */
  var gCountry = svgEl('g', { 'class': 'jm-country' }, svg);
  map.paths.forEach(function (d) {
    svgEl('path', { 'class': 'jm-land', d: d, 'vector-effect': 'non-scaling-stroke' }, gCountry);
  });
  var gRoute = svgEl('g', { 'class': 'jm-route' }, svg);

  var upcomingEl = upcoming.length ? svgEl('path', { 'class': 'jm-route-upcoming' }, gRoute) : null;
  var baseEls = stops.slice(1).map(function () {
    return svgEl('path', { 'class': 'jm-leg-base' }, gRoute);
  });
  var fillEls = stops.slice(1).map(function () {
    return svgEl('path', { 'class': 'jm-leg-fill' }, gRoute);
  });
  var upcomingStopEls = upcoming.map(function (u) {
    var c = svgEl('circle', { 'class': 'jm-stop-upcoming', r: 4 }, gRoute);
    u.labelEl = svgEl('text', { 'class': 'jm-label jm-label-upcoming' }, gRoute);
    u.labelEl.textContent = u.label;
    return c;
  });
  var stopEls = stops.map(function (s) {
    var c = svgEl('circle', { 'class': 'jm-stop', r: 5 }, gRoute);
    s.labelEl = svgEl('text', { 'class': 'jm-label' }, gRoute);
    s.labelEl.textContent = s.label;
    return c;
  });

  // the anchored "you are here" point — the map moves, this doesn't
  var halo = svgEl('circle', { 'class': 'jm-marker-halo', r: 9 }, svg);
  var marker = svgEl('circle', { 'class': 'jm-marker', r: 5.5 }, svg);

  document.body.appendChild(container);

  /* ---- Layout: scale + anchor, recomputed on resize ---- */
  var scale = 1;
  var anchorX = 0;
  var anchorY = 0;
  var legs = [];

  function placeLabel(s, p) {
    var left = s.side !== 'right';
    s.labelEl.setAttribute('x', (left ? p.x - 11 : p.x + 11).toFixed(1));
    s.labelEl.setAttribute('y', (p.y + 4).toFixed(1));
    s.labelEl.setAttribute('text-anchor', left ? 'end' : 'start');
  }

  function layout() {
    var vh = window.innerHeight;
    scale = (vh * MAP_VH) / map.height;
    // on phones the content margin is slim — keep the marker on screen
    anchorX = Math.max(14, article.getBoundingClientRect().left + DOT_X);
    anchorY = vh * REF;

    stops.forEach(function (s) { s.px = { x: s.ux * scale, y: s.uy * scale }; });
    upcoming.forEach(function (u) { u.px = { x: u.ux * scale, y: u.uy * scale }; });

    legs = [];
    for (var i = 0; i < stops.length - 1; i++) legs.push(buildLeg(stops[i].px, stops[i + 1].px));
    legs.forEach(function (leg, j) {
      baseEls[j].setAttribute('d', legD(leg));
      fillEls[j].setAttribute('d', legD(leg));
      fillEls[j].setAttribute('stroke-dasharray', leg.len.toFixed(1));
    });

    if (upcomingEl) {
      var from = stops[stops.length - 1].px;
      var d = '';
      upcoming.forEach(function (u) {
        var leg = buildLeg(from, u.px);
        d += legD(leg);
        from = u.px;
      });
      upcomingEl.setAttribute('d', d);
    }

    stops.forEach(function (s, j) {
      stopEls[j].setAttribute('cx', s.px.x.toFixed(1));
      stopEls[j].setAttribute('cy', s.px.y.toFixed(1));
      placeLabel(s, s.px);
    });
    upcoming.forEach(function (u, j) {
      upcomingStopEls[j].setAttribute('cx', u.px.x.toFixed(1));
      upcomingStopEls[j].setAttribute('cy', u.px.y.toFixed(1));
      placeLabel(u, u.px);
    });

    marker.setAttribute('cx', anchorX.toFixed(1));
    marker.setAttribute('cy', anchorY.toFixed(1));
    halo.setAttribute('cx', anchorX.toFixed(1));
    halo.setAttribute('cy', anchorY.toFixed(1));
  }

  /* ---- Scroll → progress → pan ---- */
  function easeInOut(t) {
    return t < 0.5 ? 2 * t * t : 1 - Math.pow(-2 * t + 2, 2) / 2;
  }

  function tick() {
    ticking = false;
    if (container.offsetWidth === 0) return; // hidden by the responsive breakpoint

    var vh = window.innerHeight;
    var refY = vh * REF;

    var aRect = article.getBoundingClientRect();
    var visible = aRect.top < vh * 0.45 && aRect.bottom > vh * 0.3;
    container.classList.toggle('jm-visible', visible);
    if (!visible) return;

    var tops = stops.map(function (s) { return s.el.getBoundingClientRect().top; });

    // index of the current leg + eased progress along it
    var seg = 0;
    var frac = 0;
    if (tops[0] >= refY) {
      seg = 0; frac = 0;
    } else if (tops[tops.length - 1] < refY) {
      seg = legs.length - 1; frac = 1;
    } else {
      for (var i = 0; i < legs.length; i++) {
        if (tops[i] < refY && tops[i + 1] >= refY) {
          var t = (refY - tops[i]) / (tops[i + 1] - tops[i]);
          seg = i;
          // rest on the stop while its section is being read
          frac = t <= DWELL ? 0 : easeInOut((t - DWELL) / (1 - DWELL));
          break;
        }
      }
    }

    legs.forEach(function (leg, j) {
      var off = j < seg ? 0 : j > seg ? leg.len : leg.len * (1 - frac);
      fillEls[j].setAttribute('stroke-dashoffset', off.toFixed(1));
    });

    // pan the country so the current position sits under the anchored marker
    var p = frac >= 1 ? stops[seg + 1].px : pointAtFraction(legs[seg], frac);
    var tx = anchorX - p.x;
    var ty = anchorY - p.y;
    gCountry.setAttribute('transform',
      'translate(' + tx.toFixed(2) + ' ' + ty.toFixed(2) + ') scale(' + scale.toFixed(4) + ')');
    gRoute.setAttribute('transform', 'translate(' + tx.toFixed(2) + ' ' + ty.toFixed(2) + ')');

    var current = -1;
    stops.forEach(function (s, j) {
      var reached = tops[j] < refY || j === 0;
      stopEls[j].classList.toggle('jm-reached', reached);
      s.labelEl.classList.toggle('jm-reached', reached);
      if (reached) current = j;
    });
    stopEls.forEach(function (el, j) { el.classList.toggle('jm-current', j === current); });
  }

  var ticking = false;
  function schedule() {
    if (!ticking) {
      ticking = true;
      window.requestAnimationFrame(tick);
    }
  }

  function relayout() {
    layout();
    schedule();
  }

  window.addEventListener('scroll', schedule, { passive: true });
  window.addEventListener('resize', relayout);
  window.addEventListener('load', relayout);
  document.addEventListener('langchange', schedule);
  layout();
  schedule();
})();
