/*
 * Journey map — scroll-following travel itinerary
 * --------------------------------------------------------------------------
 * Renders a fixed white/grey country map in the page gutter of a travel
 * post. Green stops and a route line trace the itinerary: as the reader
 * scrolls, a position marker travels from city to city, pausing on each
 * stop while its diary section is on screen. The drawn route ends at the
 * last published stop; upcoming stops are sketched in dotted grey.
 *
 * Inputs (set by the page before this script runs):
 *   window.__JOURNEY__          { outline, accent, stops[], upcoming[] }
 *   window.__JOURNEY_OUTLINES__ projected country paths + projection params
 *                               (generated by _src/tools/journey/build-outline.mjs)
 *
 * Stops carry plain lat/lng; they are projected here with the same
 * plate-carrée parameters used for the outline. Each stop's `anchor` is the
 * id of its section heading in the article — scroll progress is measured
 * against those headings, so the map needs no per-post pixel tuning.
 * Purely decorative: aria-hidden, pointer-events none, desktop only.
 */
(function () {
  'use strict';

  var cfg = window.__JOURNEY__;
  var outlines = window.__JOURNEY_OUTLINES__;
  if (!cfg || !outlines || !outlines[cfg.outline]) return;
  var map = outlines[cfg.outline];

  var article = document.querySelector('.post-content');
  if (!article) return;

  var SVG_NS = 'http://www.w3.org/2000/svg';
  var DWELL = 0.5; // fraction of each section spent parked on its stop

  function project(s) {
    return {
      x: (s.lng - map.proj.lng0) * map.proj.kx,
      y: (map.proj.lat1 - s.lat) * map.proj.ky
    };
  }

  var stops = cfg.stops
    .map(function (s) {
      var el = document.getElementById(s.anchor);
      if (!el) return null;
      var p = project(s);
      return { label: s.label, side: s.labelSide || 'left', x: p.x, y: p.y, el: el };
    })
    .filter(Boolean);
  if (stops.length < 2) return;

  var upcoming = (cfg.upcoming || []).map(function (s) {
    var p = project(s);
    return { label: s.label, side: s.labelSide || 'left', x: p.x, y: p.y };
  });

  /* ---- Leg geometry: gentle quadratic bow toward the seaward (east) side.
     Arc lengths are sampled so marker position and stroke reveal agree
     without touching the DOM (the map may start out display:none). ---- */
  function quadAt(leg, t) {
    var u = 1 - t;
    return {
      x: u * u * leg.a.x + 2 * u * t * leg.c.x + t * t * leg.b.x,
      y: u * u * leg.a.y + 2 * u * t * leg.c.y + t * t * leg.b.y
    };
  }

  function buildLeg(a, b) {
    var dx = b.x - a.x;
    var dy = b.y - a.y;
    var span = Math.sqrt(dx * dx + dy * dy) || 1;
    var nx = dy / span;
    var ny = -dx / span;
    if (nx < 0) { nx = -nx; ny = -ny; } // bow east
    if (Math.abs(nx) < 0.25 && ny > 0) { nx = -nx; ny = -ny; } // near-horizontal: bow north
    var bow = Math.min(13, span * 0.18);
    var leg = {
      a: a,
      b: b,
      c: { x: (a.x + b.x) / 2 + nx * bow, y: (a.y + b.y) / 2 + ny * bow }
    };
    var N = 48;
    var cum = [0];
    var prev = a;
    for (var i = 1; i <= N; i++) {
      var p = quadAt(leg, i / N);
      cum.push(cum[i - 1] + Math.hypot(p.x - prev.x, p.y - prev.y));
      prev = p;
    }
    leg.samples = cum;
    leg.len = cum[N];
    return leg;
  }

  /* Point at a given arc-length fraction (lookup + lerp) */
  function pointAtFraction(leg, f) {
    var target = f * leg.len;
    var cum = leg.samples;
    var lo = 0;
    var hi = cum.length - 1;
    while (lo < hi - 1) {
      var mid = (lo + hi) >> 1;
      if (cum[mid] < target) lo = mid; else hi = mid;
    }
    var seg = cum[hi] - cum[lo] || 1;
    var t = (lo + (target - cum[lo]) / seg) / (cum.length - 1);
    return quadAt(leg, t);
  }

  function legD(leg) {
    return 'M' + leg.a.x.toFixed(1) + ' ' + leg.a.y.toFixed(1) +
      'Q' + leg.c.x.toFixed(1) + ' ' + leg.c.y.toFixed(1) +
      ' ' + leg.b.x.toFixed(1) + ' ' + leg.b.y.toFixed(1);
  }

  var legs = [];
  for (var i = 0; i < stops.length - 1; i++) legs.push(buildLeg(stops[i], stops[i + 1]));

  /* ---- Build the SVG ---- */
  function svgEl(tag, attrs, parent) {
    var el = document.createElementNS(SVG_NS, tag);
    for (var k in attrs) el.setAttribute(k, attrs[k]);
    if (parent) parent.appendChild(el);
    return el;
  }

  var container = document.createElement('div');
  container.className = 'journey-map';
  container.setAttribute('aria-hidden', 'true');
  if (cfg.accent) container.style.setProperty('--jm-accent', cfg.accent);

  var svg = svgEl('svg', { viewBox: '0 0 ' + map.width + ' ' + map.height }, container);

  var country = svgEl('g', { 'class': 'jm-country' }, svg);
  map.paths.forEach(function (d) { svgEl('path', { 'class': 'jm-land', d: d }, country); });

  // dotted continuation through upcoming stops
  if (upcoming.length) {
    var from = stops[stops.length - 1];
    var d = '';
    upcoming.forEach(function (u) {
      var leg = buildLeg(from, u);
      d += legD(leg);
      from = u;
    });
    svgEl('path', { 'class': 'jm-route-upcoming', d: d }, svg);
  }

  var baseEls = legs.map(function (leg) {
    return svgEl('path', { 'class': 'jm-leg-base', d: legD(leg) }, svg);
  });
  var fillEls = legs.map(function (leg) {
    return svgEl('path', {
      'class': 'jm-leg-fill',
      d: legD(leg),
      'stroke-dasharray': leg.len.toFixed(1),
      'stroke-dashoffset': leg.len.toFixed(1)
    }, svg);
  });

  function addLabel(s, cls) {
    var left = s.side !== 'right';
    svgEl('text', {
      'class': cls,
      x: (left ? s.x - 8 : s.x + 8).toFixed(1),
      y: (s.y + 3.5).toFixed(1),
      'text-anchor': left ? 'end' : 'start'
    }, svg).textContent = s.label;
  }

  upcoming.forEach(function (u) {
    svgEl('circle', { 'class': 'jm-stop-upcoming', cx: u.x.toFixed(1), cy: u.y.toFixed(1), r: 3 }, svg);
    addLabel(u, 'jm-label jm-label-upcoming');
  });

  var stopEls = stops.map(function (s) {
    var c = svgEl('circle', { 'class': 'jm-stop', cx: s.x.toFixed(1), cy: s.y.toFixed(1), r: 4 }, svg);
    addLabel(s, 'jm-label');
    s.labelEl = svg.lastChild;
    return c;
  });

  var halo = svgEl('circle', { 'class': 'jm-marker-halo', r: 7 }, svg);
  var marker = svgEl('circle', { 'class': 'jm-marker', r: 4.5 }, svg);

  document.body.appendChild(container);

  /* ---- Scroll → progress ---- */
  function easeInOut(t) {
    return t < 0.5 ? 2 * t * t : 1 - Math.pow(-2 * t + 2, 2) / 2;
  }

  function setMarker(p) {
    marker.setAttribute('cx', p.x.toFixed(2));
    marker.setAttribute('cy', p.y.toFixed(2));
    halo.setAttribute('cx', p.x.toFixed(2));
    halo.setAttribute('cy', p.y.toFixed(2));
  }

  function tick() {
    ticking = false;
    if (container.offsetWidth === 0) return; // hidden by the responsive breakpoint

    var vh = window.innerHeight;
    var refY = vh * 0.42;

    var aRect = article.getBoundingClientRect();
    var visible = aRect.top < vh * 0.45 && aRect.bottom > vh * 0.3;
    container.classList.toggle('jm-visible', visible);
    if (!visible) return;

    var tops = stops.map(function (s) { return s.el.getBoundingClientRect().top; });

    // index of the current leg + eased progress along it
    var seg = 0;
    var frac = 0;
    if (tops[0] >= refY) {
      seg = 0; frac = 0;
    } else if (tops[tops.length - 1] < refY) {
      seg = legs.length - 1; frac = 1;
    } else {
      for (var i = 0; i < legs.length; i++) {
        if (tops[i] < refY && tops[i + 1] >= refY) {
          var t = (refY - tops[i]) / (tops[i + 1] - tops[i]);
          seg = i;
          // dwell on the stop while its section is being read
          frac = t <= DWELL ? 0 : easeInOut((t - DWELL) / (1 - DWELL));
          break;
        }
      }
    }

    legs.forEach(function (leg, j) {
      var off = j < seg ? 0 : j > seg ? leg.len : leg.len * (1 - frac);
      fillEls[j].setAttribute('stroke-dashoffset', off.toFixed(1));
    });

    setMarker(frac >= 1 ? stops[seg + 1] : pointAtFraction(legs[seg], frac));

    var current = -1;
    stops.forEach(function (s, j) {
      var reached = tops[j] < refY || (j === 0 && visible);
      stopEls[j].classList.toggle('jm-reached', reached);
      s.labelEl.classList.toggle('jm-reached', reached);
      if (reached) current = j;
    });
    stopEls.forEach(function (el, j) { el.classList.toggle('jm-current', j === current); });
  }

  var ticking = false;
  function schedule() {
    if (!ticking) {
      ticking = true;
      window.requestAnimationFrame(tick);
    }
  }

  window.addEventListener('scroll', schedule, { passive: true });
  window.addEventListener('resize', schedule);
  window.addEventListener('load', schedule);
  document.addEventListener('langchange', schedule);
  setMarker(stops[0]);
  schedule();
})();
