/*
 * Journey map — giant scroll-following background (travel posts)
 * --------------------------------------------------------------------------
 * Draws a regional atlas sheet as a huge, faint grey background behind the
 * diary: the country in white with a 10m coastline, neighbouring countries
 * a shade darker, a light sea tint, the Mekong and Red River, and discreet
 * country name labels. The reader's position is pinned to the diary
 * timeline-dot column on the left of the days: the marker stays anchored
 * there while the map glides behind the text. The itinerary follows the
 * actual road network between cities (routed at build time); while a city's
 * section is on screen the map rests, and crossing into the next city the
 * map slides so the next stop arrives under the marker. The drawn route
 * ends at the last published stop; the remaining legs are dotted grey.
 *
 * Inputs (set by the page before this script runs):
 *   window.__JOURNEY__          { outline, stops[], upcoming[] }
 *   window.__JOURNEY_OUTLINES__ projected map sheet + projection params
 *                               (generated by _src/tools/journey/build-map.mjs)
 *
 * Stops carry plain lat/lng; they are projected here with the same
 * plate-carrée parameters used for the sheet. `route` legs are ordered:
 * leg i connects stop i → i+1, and legs beyond the published stops form
 * the dotted "upcoming" continuation. Each stop's `anchor` is the id of
 * its section heading in the article — scroll progress is measured against
 * those headings, so the map needs no per-post pixel tuning.
 * Purely decorative: aria-hidden, pointer-events none.
 */
(function () {
  'use strict';

  var cfg = window.__JOURNEY__;
  var outlines = window.__JOURNEY_OUTLINES__;
  if (!cfg || !outlines || !outlines[cfg.outline]) return;
  var map = outlines[cfg.outline];

  var article = document.querySelector('.post-content');
  if (!article) return;

  var SVG_NS = 'http://www.w3.org/2000/svg';
  var DWELL = 0.6; // fraction of each section spent resting on its stop
  var REF = 0.42; // reading line, as a fraction of viewport height
  var MAP_VH = 2.0; // Vietnam's height relative to the viewport — "giant"
  var DOT_X = -16; // anchor just left of the diary day-dot column, clear of headings

  function project(s) {
    return {
      x: (s.lng - map.proj.lng0) * map.proj.kx,
      y: (map.proj.lat1 - s.lat) * map.proj.ky
    };
  }

  var stops = cfg.stops
    .map(function (s) {
      var el = document.getElementById(s.anchor);
      if (!el) return null;
      var p = project(s);
      return { label: s.label, side: s.labelSide || 'left', ux: p.x, uy: p.y, el: el };
    })
    .filter(Boolean);
  if (stops.length < 2) return;

  var upcoming = (cfg.upcoming || []).map(function (s) {
    var p = project(s);
    return { label: s.label, side: s.labelSide || 'right', ux: p.x, uy: p.y };
  });

  /* ---- Legs: road polylines from the sheet (unit coords), scaled to px on
     layout. Cumulative arc lengths keep marker position and stroke reveal
     in agreement. Leg i connects stop i → i+1; extras are upcoming. ---- */
  var routeUnits = map.route || [];
  var publishedLegCount = Math.min(stops.length - 1, routeUnits.length);

  function buildLeg(pts) {
    var cum = [0];
    for (var i = 1; i < pts.length; i++) {
      cum.push(cum[i - 1] + Math.hypot(pts[i][0] - pts[i - 1][0], pts[i][1] - pts[i - 1][1]));
    }
    return { pts: pts, samples: cum, len: cum[cum.length - 1] };
  }

  /* Point at a given arc-length fraction (lookup + lerp) */
  function pointAtFraction(leg, f) {
    var target = f * leg.len;
    var cum = leg.samples;
    var lo = 0;
    var hi = cum.length - 1;
    while (lo < hi - 1) {
      var mid = (lo + hi) >> 1;
      if (cum[mid] < target) lo = mid; else hi = mid;
    }
    var span = cum[hi] - cum[lo] || 1;
    var t = (target - cum[lo]) / span;
    return {
      x: leg.pts[lo][0] + (leg.pts[hi][0] - leg.pts[lo][0]) * t,
      y: leg.pts[lo][1] + (leg.pts[hi][1] - leg.pts[lo][1]) * t
    };
  }

  function legD(leg) {
    var d = '';
    leg.pts.forEach(function (p, i) {
      d += (i === 0 ? 'M' : 'L') + p[0].toFixed(1) + ' ' + p[1].toFixed(1);
    });
    return d;
  }

  /* ---- Build the SVG ---- */
  function svgEl(tag, attrs, parent) {
    var el = document.createElementNS(SVG_NS, tag);
    for (var k in attrs) el.setAttribute(k, attrs[k]);
    if (parent) parent.appendChild(el);
    return el;
  }

  var container = document.createElement('div');
  container.className = 'journey-map';
  container.setAttribute('aria-hidden', 'true');

  var svg = svgEl('svg', {}, container);

  /* The atlas sheet keeps its generated unit coordinates and is scaled by
     transform (crisp 1px lines via non-scaling strokes). The route layer is
     rebuilt in screen px on resize, so dashes, dots and labels keep their
     natural size. Both layers share the same pan. */
  var gSheet = svgEl('g', { 'class': 'jm-sheet' }, svg);
  svgEl('rect', { 'class': 'jm-sea', x: -4000, y: -4000, width: 9000, height: 9000 }, gSheet);
  (map.neighbors || []).forEach(function (d) {
    svgEl('path', { 'class': 'jm-neighbor', d: d, 'vector-effect': 'non-scaling-stroke' }, gSheet);
  });
  (map.rivers || []).forEach(function (d) {
    svgEl('path', { 'class': 'jm-river', d: d, 'vector-effect': 'non-scaling-stroke' }, gSheet);
  });
  var gFocus = svgEl('g', { 'class': 'jm-focus' }, gSheet);
  (map.focus || map.paths || []).forEach(function (d) {
    svgEl('path', { 'class': 'jm-land', d: d, 'vector-effect': 'non-scaling-stroke' }, gFocus);
  });
  var gRoute = svgEl('g', { 'class': 'jm-route' }, svg);

  var geoLabelEls = (map.labels || []).map(function (l) {
    var t = svgEl('text', { 'class': 'jm-geo-label' }, gRoute);
    t.textContent = l.name;
    return t;
  });

  var upcomingEl = routeUnits.length > publishedLegCount
    ? svgEl('path', { 'class': 'jm-route-upcoming' }, gRoute) : null;
  var baseEls = [];
  var fillEls = [];
  for (var li = 0; li < publishedLegCount; li++) {
    baseEls.push(svgEl('path', { 'class': 'jm-leg-base' }, gRoute));
  }
  for (li = 0; li < publishedLegCount; li++) {
    fillEls.push(svgEl('path', { 'class': 'jm-leg-fill' }, gRoute));
  }
  var upcomingStopEls = upcoming.map(function (u) {
    var c = svgEl('circle', { 'class': 'jm-stop-upcoming', r: 4 }, gRoute);
    u.labelEl = svgEl('text', { 'class': 'jm-label jm-label-upcoming' }, gRoute);
    u.labelEl.textContent = u.label;
    return c;
  });
  var stopEls = stops.map(function (s) {
    var c = svgEl('circle', { 'class': 'jm-stop', r: 5 }, gRoute);
    s.labelEl = svgEl('text', { 'class': 'jm-label' }, gRoute);
    s.labelEl.textContent = s.label;
    return c;
  });

  // the anchored "you are here" point — the map moves, this doesn't
  var halo = svgEl('circle', { 'class': 'jm-marker-halo', r: 9 }, svg);
  var marker = svgEl('circle', { 'class': 'jm-marker', r: 5.5 }, svg);

  document.body.appendChild(container);

  /* ---- Layout: scale + anchor, recomputed on resize ---- */
  var scale = 1;
  var anchorX = 0;
  var anchorY = 0;
  var legs = [];

  function placeLabel(s, p) {
    var left = s.side !== 'right';
    s.labelEl.setAttribute('x', (left ? p.x - 11 : p.x + 11).toFixed(1));
    s.labelEl.setAttribute('y', (p.y + 4).toFixed(1));
    s.labelEl.setAttribute('text-anchor', left ? 'end' : 'start');
  }

  function layout() {
    var vh = window.innerHeight;
    scale = (vh * MAP_VH) / (map.focusH || map.height);
    // on phones the content margin is slim — keep the marker on screen
    anchorX = Math.max(14, article.getBoundingClientRect().left + DOT_X);
    anchorY = vh * REF;

    stops.forEach(function (s) { s.px = { x: s.ux * scale, y: s.uy * scale }; });
    upcoming.forEach(function (u) { u.px = { x: u.ux * scale, y: u.uy * scale }; });

    legs = routeUnits.map(function (pts) {
      return buildLeg(pts.map(function (p) { return [p[0] * scale, p[1] * scale]; }));
    });
    legs.slice(0, publishedLegCount).forEach(function (leg, j) {
      baseEls[j].setAttribute('d', legD(leg));
      fillEls[j].setAttribute('d', legD(leg));
      fillEls[j].setAttribute('stroke-dasharray', leg.len.toFixed(1));
    });
    if (upcomingEl) {
      var d = '';
      legs.slice(publishedLegCount).forEach(function (leg) { d += legD(leg); });
      upcomingEl.setAttribute('d', d);
    }

    stops.forEach(function (s, j) {
      stopEls[j].setAttribute('cx', s.px.x.toFixed(1));
      stopEls[j].setAttribute('cy', s.px.y.toFixed(1));
      placeLabel(s, s.px);
    });
    upcoming.forEach(function (u, j) {
      upcomingStopEls[j].setAttribute('cx', u.px.x.toFixed(1));
      upcomingStopEls[j].setAttribute('cy', u.px.y.toFixed(1));
      placeLabel(u, u.px);
    });
    (map.labels || []).forEach(function (l, j) {
      geoLabelEls[j].setAttribute('x', (l.x * scale).toFixed(1));
      geoLabelEls[j].setAttribute('y', (l.y * scale).toFixed(1));
    });

    marker.setAttribute('cx', anchorX.toFixed(1));
    marker.setAttribute('cy', anchorY.toFixed(1));
    halo.setAttribute('cx', anchorX.toFixed(1));
    halo.setAttribute('cy', anchorY.toFixed(1));
  }

  /* ---- Scroll → progress → pan ---- */
  function easeInOut(t) {
    return t < 0.5 ? 2 * t * t : 1 - Math.pow(-2 * t + 2, 2) / 2;
  }

  function tick() {
    ticking = false;
    if (container.offsetWidth === 0) return;

    var vh = window.innerHeight;
    var refY = vh * REF;

    var aRect = article.getBoundingClientRect();
    var visible = aRect.top < vh * 0.45 && aRect.bottom > vh * 0.3;
    container.classList.toggle('jm-visible', visible);
    if (!visible) return;

    var tops = stops.map(function (s) { return s.el.getBoundingClientRect().top; });

    // index of the current leg + eased progress along it
    var seg = 0;
    var frac = 0;
    if (tops[0] >= refY) {
      seg = 0; frac = 0;
    } else if (tops[tops.length - 1] < refY) {
      seg = publishedLegCount - 1; frac = 1;
    } else {
      for (var i = 0; i < publishedLegCount; i++) {
        if (tops[i] < refY && tops[i + 1] >= refY) {
          var t = (refY - tops[i]) / (tops[i + 1] - tops[i]);
          seg = i;
          // rest on the stop while its section is being read
          frac = t <= DWELL ? 0 : easeInOut((t - DWELL) / (1 - DWELL));
          break;
        }
      }
    }

    for (var j = 0; j < publishedLegCount; j++) {
      var off = j < seg ? 0 : j > seg ? legs[j].len : legs[j].len * (1 - frac);
      fillEls[j].setAttribute('stroke-dashoffset', off.toFixed(1));
    }

    // pan the sheet so the current position sits under the anchored marker
    var p = frac >= 1 ? stops[seg + 1].px : pointAtFraction(legs[seg], frac);
    var tx = anchorX - p.x;
    var ty = anchorY - p.y;
    gSheet.setAttribute('transform',
      'translate(' + tx.toFixed(2) + ' ' + ty.toFixed(2) + ') scale(' + scale.toFixed(4) + ')');
    gRoute.setAttribute('transform', 'translate(' + tx.toFixed(2) + ' ' + ty.toFixed(2) + ')');

    var current = -1;
    stops.forEach(function (s, k) {
      var reached = tops[k] < refY || k === 0;
      stopEls[k].classList.toggle('jm-reached', reached);
      s.labelEl.classList.toggle('jm-reached', reached);
      if (reached) current = k;
    });
    stopEls.forEach(function (el, k) { el.classList.toggle('jm-current', k === current); });
  }

  var ticking = false;
  function schedule() {
    if (!ticking) {
      ticking = true;
      window.requestAnimationFrame(tick);
    }
  }

  function relayout() {
    layout();
    schedule();
  }

  window.addEventListener('scroll', schedule, { passive: true });
  window.addEventListener('resize', relayout);
  window.addEventListener('load', relayout);
  document.addEventListener('langchange', schedule);
  layout();
  schedule();
})();
